#!/usr/bin/env python3

import sys
import re
import base64
from pathlib import Path
import mimetypes
data_map = {}

args = sys.argv
if len(args) > 0 and Path(args[0]) == Path(__file__).name:
    del args[0]

if len(args) != 2:
    print(f"""Usage:
    Arg 1: File which relative paths to replace with
    Arg 2: data:mime/type:base64,
    Args given: {args}""")
    exit()

md_file, resource_dir = args
md_file = Path(md_file)
with open(md_file) as f:
    file_data = f.read()


for f in Path(resource_dir).glob("*"):
    mime_type, _ = mimetypes.guess_type(f)
    regex = re.compile(f"(\\./)?{f}")
    with f.open("rb") as data_file:
        file_data = regex.sub(
            f"data:{mime_type};base64,"+
                base64.b64encode(data_file.read()).decode("ascii"), 
            file_data)

sys.stdout.write(file_data)
